
name: MPS-QA_CI

on: [push, pull_request]

env:
  MPS_VER: "2020.3"
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.MPSQA_GITHUB_PKG_REGISTRY }}

jobs:
  build_mps_qa_packages:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Gradle
      run: |
        chmod +x ./gradlew
        
    - name: Setup headless environment
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
       
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11  
        
    - name: Build MPS-QA
      uses: gradle/gradle-build-action@v1.3.3
      with: 
        arguments: build_allInOne_package -Pgpr.user=${{github.actor}} -Pgpr.token=${{ secrets.GITHUB_TOKEN }}
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        dependencies-cache-key: gradle/dependency-locks/**
        dependencies-cache-exact: true
        configuration-cache-enabled: true
        gradle-executable: /home/runner/work/mps-qa/mps-qa/gradlew
        
    - name: Archive distribution
      uses: actions/upload-artifact@v2
      with:
        name: mpsqa-distribution-2020.3-${{ steps.time.outputs.time }}
        path: build/artifacts/mps-qa/mps-qa-2020.3-SNAPSHOT.zip